// <auto-generated />
using ApiCereals;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCereals.Migrations
{
    [DbContext(typeof(CerealDbContext))]
    [Migration("20220323105954_ex01-compatibility-mickael-api_1")]
    partial class ex01compatibilitymickaelapi_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiCereals.Models.Cereal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte>("Calories")
                        .HasColumnType("tinyint");

                    b.Property<short>("Carbo")
                        .HasColumnType("smallint");

                    b.Property<byte>("Fiber")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<short>("Potass")
                        .HasColumnType("smallint");

                    b.Property<byte>("Protein")
                        .HasColumnType("tinyint");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Sodium")
                        .HasColumnType("int");

                    b.Property<short>("Sugars")
                        .HasColumnType("smallint");

                    b.Property<int>("Vitamins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tata");
                });
#pragma warning restore 612, 618
        }
    }
}
